# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main_window.ui'
##
## Created by: Qt User Interface Compiler version 6.11.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QAbstractItemView, QAbstractScrollArea, QApplication, QFrame,
    QHeaderView, QLabel, QMainWindow, QMenu,
    QMenuBar, QProgressBar, QPushButton, QSizePolicy,
    QStatusBar, QTableWidget, QTableWidgetItem, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.setWindowModality(Qt.NonModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(1000, 600)
        MainWindow.setMinimumSize(QSize(1000, 600))
        MainWindow.setMaximumSize(QSize(1000, 600))
        MainWindow.setMouseTracking(False)
        MainWindow.setTabletTracking(False)
        MainWindow.setAcceptDrops(False)
        MainWindow.setAutoFillBackground(True)
        MainWindow.setDocumentMode(True)
        self.actionNew = QAction(MainWindow)
        self.actionNew.setObjectName(u"actionNew")
        self.actionSave = QAction(MainWindow)
        self.actionSave.setObjectName(u"actionSave")
        self.actionSave_as = QAction(MainWindow)
        self.actionSave_as.setObjectName(u"actionSave_as")
        self.actionQuit = QAction(MainWindow)
        self.actionQuit.setObjectName(u"actionQuit")
        self.actionQuit.setCheckable(False)
        self.actionQuit.setShortcutVisibleInContextMenu(False)
        self.actionGenerate_files = QAction(MainWindow)
        self.actionGenerate_files.setObjectName(u"actionGenerate_files")
        self.actionUser_ = QAction(MainWindow)
        self.actionUser_.setObjectName(u"actionUser_")
        self.actionUser_Manual_2 = QAction(MainWindow)
        self.actionUser_Manual_2.setObjectName(u"actionUser_Manual_2")
        self.actionInfo = QAction(MainWindow)
        self.actionInfo.setObjectName(u"actionInfo")
        self.actionEeprom = QAction(MainWindow)
        self.actionEeprom.setObjectName(u"actionEeprom")
        self.actionUser_Manual = QAction(MainWindow)
        self.actionUser_Manual.setObjectName(u"actionUser_Manual")
        self.actionInformation = QAction(MainWindow)
        self.actionInformation.setObjectName(u"actionInformation")
        self.actionImport = QAction(MainWindow)
        self.actionImport.setObjectName(u"actionImport")
        self.actionOpenFile = QAction(MainWindow)
        self.actionOpenFile.setObjectName(u"actionOpenFile")
        self.actionQuit_2 = QAction(MainWindow)
        self.actionQuit_2.setObjectName(u"actionQuit_2")
        self.actionAdd_new_element = QAction(MainWindow)
        self.actionAdd_new_element.setObjectName(u"actionAdd_new_element")
        self.actionDelete_an_element = QAction(MainWindow)
        self.actionDelete_an_element.setObjectName(u"actionDelete_an_element")
        self.actionDelete_all = QAction(MainWindow)
        self.actionDelete_all.setObjectName(u"actionDelete_all")
        self.actionGenerate_h_files = QAction(MainWindow)
        self.actionGenerate_h_files.setObjectName(u"actionGenerate_h_files")
        self.actionGenerate_xml_files = QAction(MainWindow)
        self.actionGenerate_xml_files.setObjectName(u"actionGenerate_xml_files")
        self.actionProject = QAction(MainWindow)
        self.actionProject.setObjectName(u"actionProject")
        self.actionGenerate_all = QAction(MainWindow)
        self.actionGenerate_all.setObjectName(u"actionGenerate_all")
        self.actionQuit_3 = QAction(MainWindow)
        self.actionQuit_3.setObjectName(u"actionQuit_3")
        self.actionExit = QAction(MainWindow)
        self.actionExit.setObjectName(u"actionExit")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.centralwidget.setEnabled(True)
        font = QFont()
        font.setKerning(True)
        self.centralwidget.setFont(font)
        self.MemoryUsage_progressBar = QProgressBar(self.centralwidget)
        self.MemoryUsage_progressBar.setObjectName(u"MemoryUsage_progressBar")
        self.MemoryUsage_progressBar.setGeometry(QRect(10, 480, 971, 23))
        self.MemoryUsage_progressBar.setValue(0)
        self.EepromMemoryUsageText = QLabel(self.centralwidget)
        self.EepromMemoryUsageText.setObjectName(u"EepromMemoryUsageText")
        self.EepromMemoryUsageText.setGeometry(QRect(10, 450, 171, 31))
        font1 = QFont()
        font1.setPointSize(12)
        self.EepromMemoryUsageText.setFont(font1)
        self.AddElementpushButton = QPushButton(self.centralwidget)
        self.AddElementpushButton.setObjectName(u"AddElementpushButton")
        self.AddElementpushButton.setGeometry(QRect(10, 410, 131, 31))
        self.DeleteElementpushButton = QPushButton(self.centralwidget)
        self.DeleteElementpushButton.setObjectName(u"DeleteElementpushButton")
        self.DeleteElementpushButton.setGeometry(QRect(160, 410, 131, 31))
        self.EepromMemoryConfigurationText = QLabel(self.centralwidget)
        self.EepromMemoryConfigurationText.setObjectName(u"EepromMemoryConfigurationText")
        self.EepromMemoryConfigurationText.setGeometry(QRect(10, 0, 321, 51))
        font2 = QFont()
        font2.setPointSize(20)
        font2.setBold(True)
        font2.setItalic(False)
        font2.setStrikeOut(False)
        self.EepromMemoryConfigurationText.setFont(font2)
        self.DeleteAllpushButton = QPushButton(self.centralwidget)
        self.DeleteAllpushButton.setObjectName(u"DeleteAllpushButton")
        self.DeleteAllpushButton.setGeometry(QRect(890, 410, 101, 31))
        self.EepromText = QLabel(self.centralwidget)
        self.EepromText.setObjectName(u"EepromText")
        self.EepromText.setGeometry(QRect(10, 520, 47, 21))
        font3 = QFont()
        font3.setBold(True)
        self.EepromText.setFont(font3)
        self.EepromUsageText = QLabel(self.centralwidget)
        self.EepromUsageText.setObjectName(u"EepromUsageText")
        self.EepromUsageText.setGeometry(QRect(180, 520, 47, 21))
        self.EepromUsageText.setFont(font3)
        self.EepromFreeText = QLabel(self.centralwidget)
        self.EepromFreeText.setObjectName(u"EepromFreeText")
        self.EepromFreeText.setGeometry(QRect(320, 520, 31, 21))
        self.EepromFreeText.setFont(font3)
        self.EepromSize = QLabel(self.centralwidget)
        self.EepromSize.setObjectName(u"EepromSize")
        self.EepromSize.setGeometry(QRect(60, 520, 81, 21))
        self.EepromSize.setFrameShape(QFrame.Box)
        self.EepromSize.setScaledContents(False)
        self.EepromSize.setWordWrap(False)
        self.EepromSize.setOpenExternalLinks(False)
        self.EepromSize_Used = QLabel(self.centralwidget)
        self.EepromSize_Used.setObjectName(u"EepromSize_Used")
        self.EepromSize_Used.setGeometry(QRect(230, 520, 47, 21))
        self.EepromSize_Used.setFrameShape(QFrame.Box)
        self.EepromSize_Used.setScaledContents(False)
        self.EepromSize_Used.setWordWrap(False)
        self.EepromSize_Used.setOpenExternalLinks(False)
        self.EepromSize_Free = QLabel(self.centralwidget)
        self.EepromSize_Free.setObjectName(u"EepromSize_Free")
        self.EepromSize_Free.setGeometry(QRect(360, 520, 47, 21))
        self.EepromSize_Free.setFrameShape(QFrame.Box)
        self.EepromSize_Free.setScaledContents(False)
        self.EepromSize_Free.setWordWrap(False)
        self.EepromSize_Free.setOpenExternalLinks(False)
        self.VariablesTableWidget = QTableWidget(self.centralwidget)
        if (self.VariablesTableWidget.columnCount() < 8):
            self.VariablesTableWidget.setColumnCount(8)
        __qtablewidgetitem = QTableWidgetItem()
        self.VariablesTableWidget.setHorizontalHeaderItem(0, __qtablewidgetitem)
        __qtablewidgetitem1 = QTableWidgetItem()
        self.VariablesTableWidget.setHorizontalHeaderItem(1, __qtablewidgetitem1)
        __qtablewidgetitem2 = QTableWidgetItem()
        self.VariablesTableWidget.setHorizontalHeaderItem(2, __qtablewidgetitem2)
        __qtablewidgetitem3 = QTableWidgetItem()
        self.VariablesTableWidget.setHorizontalHeaderItem(3, __qtablewidgetitem3)
        __qtablewidgetitem4 = QTableWidgetItem()
        self.VariablesTableWidget.setHorizontalHeaderItem(4, __qtablewidgetitem4)
        __qtablewidgetitem5 = QTableWidgetItem()
        self.VariablesTableWidget.setHorizontalHeaderItem(5, __qtablewidgetitem5)
        __qtablewidgetitem6 = QTableWidgetItem()
        self.VariablesTableWidget.setHorizontalHeaderItem(6, __qtablewidgetitem6)
        __qtablewidgetitem7 = QTableWidgetItem()
        self.VariablesTableWidget.setHorizontalHeaderItem(7, __qtablewidgetitem7)
        self.VariablesTableWidget.setObjectName(u"VariablesTableWidget")
        self.VariablesTableWidget.setGeometry(QRect(10, 60, 980, 330))
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.VariablesTableWidget.sizePolicy().hasHeightForWidth())
        self.VariablesTableWidget.setSizePolicy(sizePolicy)
        self.VariablesTableWidget.setMinimumSize(QSize(980, 330))
        self.VariablesTableWidget.setMaximumSize(QSize(980, 330))
        self.VariablesTableWidget.setAcceptDrops(False)
        self.VariablesTableWidget.setSizeAdjustPolicy(QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.VariablesTableWidget.setAlternatingRowColors(True)
        self.VariablesTableWidget.setTextElideMode(Qt.ElideLeft)
        self.VariablesTableWidget.setVerticalScrollMode(QAbstractItemView.ScrollPerItem)
        self.VariablesTableWidget.setGridStyle(Qt.NoPen)
        self.VariablesTableWidget.setSortingEnabled(True)
        self.VariablesTableWidget.setRowCount(0)
        self.VariablesTableWidget.horizontalHeader().setVisible(True)
        self.VariablesTableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.VariablesTableWidget.horizontalHeader().setMinimumSectionSize(40)
        self.VariablesTableWidget.horizontalHeader().setHighlightSections(True)
        self.VariablesTableWidget.horizontalHeader().setProperty(u"showSortIndicator", True)
        self.VariablesTableWidget.verticalHeader().setVisible(False)
        self.VariablesTableWidget.verticalHeader().setCascadingSectionResizes(True)
        self.VariablesTableWidget.verticalHeader().setMinimumSectionSize(20)
        self.VariablesTableWidget.verticalHeader().setHighlightSections(True)
        self.VariablesTableWidget.verticalHeader().setProperty(u"showSortIndicator", False)
        self.VariablesTableWidget.verticalHeader().setStretchLastSection(False)
        self.EepromName = QLabel(self.centralwidget)
        self.EepromName.setObjectName(u"EepromName")
        self.EepromName.setGeometry(QRect(180, 450, 261, 31))
        self.EepromName.setFont(font1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1000, 21))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuEdit = QMenu(self.menubar)
        self.menuEdit.setObjectName(u"menuEdit")
        self.menuGenerate = QMenu(self.menubar)
        self.menuGenerate.setObjectName(u"menuGenerate")
        self.menuConfigure = QMenu(self.menubar)
        self.menuConfigure.setObjectName(u"menuConfigure")
        self.menuHelp = QMenu(self.menubar)
        self.menuHelp.setObjectName(u"menuHelp")
        self.menuValidate = QMenu(self.menubar)
        self.menuValidate.setObjectName(u"menuValidate")
        MainWindow.setMenuBar(self.menubar)
        self.MemoryUsage_statusbar = QStatusBar(MainWindow)
        self.MemoryUsage_statusbar.setObjectName(u"MemoryUsage_statusbar")
        MainWindow.setStatusBar(self.MemoryUsage_statusbar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuConfigure.menuAction())
        self.menubar.addAction(self.menuValidate.menuAction())
        self.menubar.addAction(self.menuGenerate.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_as)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionOpenFile)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionAdd_new_element)
        self.menuEdit.addAction(self.actionDelete_an_element)
        self.menuEdit.addAction(self.actionDelete_all)
        self.menuGenerate.addAction(self.actionGenerate_files)
        self.menuGenerate.addAction(self.actionGenerate_h_files)
        self.menuGenerate.addAction(self.actionGenerate_all)
        self.menuConfigure.addAction(self.actionEeprom)
        self.menuHelp.addAction(self.actionUser_Manual)
        self.menuHelp.addAction(self.actionInformation)
        self.menuValidate.addAction(self.actionProject)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Eeprom Configurator", None))
        self.actionNew.setText(QCoreApplication.translate("MainWindow", u"New", None))
        self.actionSave.setText(QCoreApplication.translate("MainWindow", u"Save", None))
        self.actionSave_as.setText(QCoreApplication.translate("MainWindow", u"Save as", None))
        self.actionQuit.setText(QCoreApplication.translate("MainWindow", u"Quit", None))
        self.actionGenerate_files.setText(QCoreApplication.translate("MainWindow", u"Generate .c files", None))
        self.actionUser_.setText(QCoreApplication.translate("MainWindow", u"Eeprom memory", None))
        self.actionUser_Manual_2.setText(QCoreApplication.translate("MainWindow", u"User Manual", None))
        self.actionInfo.setText(QCoreApplication.translate("MainWindow", u"Info", None))
        self.actionEeprom.setText(QCoreApplication.translate("MainWindow", u"Eeprom parameters", None))
        self.actionUser_Manual.setText(QCoreApplication.translate("MainWindow", u"User Manual", None))
        self.actionInformation.setText(QCoreApplication.translate("MainWindow", u"Info", None))
        self.actionImport.setText(QCoreApplication.translate("MainWindow", u"Import", None))
        self.actionOpenFile.setText(QCoreApplication.translate("MainWindow", u"Open", None))
        self.actionQuit_2.setText(QCoreApplication.translate("MainWindow", u"Quit", None))
        self.actionAdd_new_element.setText(QCoreApplication.translate("MainWindow", u"Add new element", None))
        self.actionDelete_an_element.setText(QCoreApplication.translate("MainWindow", u"Delete an element", None))
        self.actionDelete_all.setText(QCoreApplication.translate("MainWindow", u"Delete all", None))
        self.actionGenerate_h_files.setText(QCoreApplication.translate("MainWindow", u"Generate .h files", None))
        self.actionGenerate_xml_files.setText(QCoreApplication.translate("MainWindow", u"Generate .xml files", None))
        self.actionProject.setText(QCoreApplication.translate("MainWindow", u"Project", None))
        self.actionGenerate_all.setText(QCoreApplication.translate("MainWindow", u"Generate all", None))
        self.actionQuit_3.setText(QCoreApplication.translate("MainWindow", u"Exit", None))
        self.actionExit.setText(QCoreApplication.translate("MainWindow", u"Exit", None))
        self.EepromMemoryUsageText.setText(QCoreApplication.translate("MainWindow", u"Eeprom Memory Usage", None))
        self.AddElementpushButton.setText(QCoreApplication.translate("MainWindow", u"Add new element", None))
        self.DeleteElementpushButton.setText(QCoreApplication.translate("MainWindow", u"Delet an element", None))
        self.EepromMemoryConfigurationText.setText(QCoreApplication.translate("MainWindow", u"Eeprom Configurator", None))
        self.DeleteAllpushButton.setText(QCoreApplication.translate("MainWindow", u"Delet all", None))
        self.EepromText.setText(QCoreApplication.translate("MainWindow", u"Eeprom:", None))
        self.EepromUsageText.setText(QCoreApplication.translate("MainWindow", u"Usaged:", None))
        self.EepromFreeText.setText(QCoreApplication.translate("MainWindow", u"Free:", None))
        self.EepromSize.setText("")
        self.EepromSize_Used.setText("")
        self.EepromSize_Free.setText("")
        ___qtablewidgetitem = self.VariablesTableWidget.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("MainWindow", u"Index", None))
        ___qtablewidgetitem1 = self.VariablesTableWidget.horizontalHeaderItem(1)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("MainWindow", u"Name", None))
        ___qtablewidgetitem2 = self.VariablesTableWidget.horizontalHeaderItem(2)
        ___qtablewidgetitem2.setText(QCoreApplication.translate("MainWindow", u"Type", None))
        ___qtablewidgetitem3 = self.VariablesTableWidget.horizontalHeaderItem(3)
        ___qtablewidgetitem3.setText(QCoreApplication.translate("MainWindow", u"Elements", None))
        ___qtablewidgetitem4 = self.VariablesTableWidget.horizontalHeaderItem(4)
        ___qtablewidgetitem4.setText(QCoreApplication.translate("MainWindow", u"Size", None))
        ___qtablewidgetitem5 = self.VariablesTableWidget.horizontalHeaderItem(5)
        ___qtablewidgetitem5.setText(QCoreApplication.translate("MainWindow", u"Address", None))
        ___qtablewidgetitem6 = self.VariablesTableWidget.horizontalHeaderItem(6)
        ___qtablewidgetitem6.setText(QCoreApplication.translate("MainWindow", u"Init Value", None))
        ___qtablewidgetitem7 = self.VariablesTableWidget.horizontalHeaderItem(7)
        ___qtablewidgetitem7.setText(QCoreApplication.translate("MainWindow", u"Comment", None))
        self.EepromName.setText("")
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuEdit.setTitle(QCoreApplication.translate("MainWindow", u"Edit", None))
        self.menuGenerate.setTitle(QCoreApplication.translate("MainWindow", u"Generate", None))
        self.menuConfigure.setTitle(QCoreApplication.translate("MainWindow", u"Configure", None))
        self.menuHelp.setTitle(QCoreApplication.translate("MainWindow", u"Help", None))
        self.menuValidate.setTitle(QCoreApplication.translate("MainWindow", u"Validate", None))
    # retranslateUi

