# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main_window.ui'
##
## Created by: Qt User Interface Compiler version 6.11.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QAbstractItemView, QAbstractScrollArea, QApplication, QHeaderView,
    QLabel, QMainWindow, QMenu, QMenuBar,
    QProgressBar, QPushButton, QSizePolicy, QStatusBar,
    QTableWidget, QTableWidgetItem, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.setWindowModality(Qt.NonModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(1000, 600)
        MainWindow.setMinimumSize(QSize(1000, 600))
        MainWindow.setMaximumSize(QSize(1000, 600))
        MainWindow.setMouseTracking(False)
        MainWindow.setTabletTracking(False)
        MainWindow.setAcceptDrops(False)
        MainWindow.setAutoFillBackground(True)
        MainWindow.setDocumentMode(True)
        self.actionNew = QAction(MainWindow)
        self.actionNew.setObjectName(u"actionNew")
        self.actionSave = QAction(MainWindow)
        self.actionSave.setObjectName(u"actionSave")
        self.actionSave_as = QAction(MainWindow)
        self.actionSave_as.setObjectName(u"actionSave_as")
        self.actionQuit = QAction(MainWindow)
        self.actionQuit.setObjectName(u"actionQuit")
        self.actionQuit.setCheckable(False)
        self.actionQuit.setShortcutVisibleInContextMenu(False)
        self.actionGenerate_files = QAction(MainWindow)
        self.actionGenerate_files.setObjectName(u"actionGenerate_files")
        self.actionUser_ = QAction(MainWindow)
        self.actionUser_.setObjectName(u"actionUser_")
        self.actionUser_Manual_2 = QAction(MainWindow)
        self.actionUser_Manual_2.setObjectName(u"actionUser_Manual_2")
        self.actionInfo = QAction(MainWindow)
        self.actionInfo.setObjectName(u"actionInfo")
        self.actionEeprom = QAction(MainWindow)
        self.actionEeprom.setObjectName(u"actionEeprom")
        self.actionUser_Manual = QAction(MainWindow)
        self.actionUser_Manual.setObjectName(u"actionUser_Manual")
        self.actionInformation = QAction(MainWindow)
        self.actionInformation.setObjectName(u"actionInformation")
        self.actionImport = QAction(MainWindow)
        self.actionImport.setObjectName(u"actionImport")
        self.actionExport = QAction(MainWindow)
        self.actionExport.setObjectName(u"actionExport")
        self.actionQuit_2 = QAction(MainWindow)
        self.actionQuit_2.setObjectName(u"actionQuit_2")
        self.actionAdd_new_element = QAction(MainWindow)
        self.actionAdd_new_element.setObjectName(u"actionAdd_new_element")
        self.actionDelete_an_element = QAction(MainWindow)
        self.actionDelete_an_element.setObjectName(u"actionDelete_an_element")
        self.actionDelete_all = QAction(MainWindow)
        self.actionDelete_all.setObjectName(u"actionDelete_all")
        self.actionGenerate_h_files = QAction(MainWindow)
        self.actionGenerate_h_files.setObjectName(u"actionGenerate_h_files")
        self.actionGenerate_xml_files = QAction(MainWindow)
        self.actionGenerate_xml_files.setObjectName(u"actionGenerate_xml_files")
        self.actionValidate_variables = QAction(MainWindow)
        self.actionValidate_variables.setObjectName(u"actionValidate_variables")
        self.actionGenerate_all = QAction(MainWindow)
        self.actionGenerate_all.setObjectName(u"actionGenerate_all")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.centralwidget.setEnabled(True)
        font = QFont()
        font.setKerning(True)
        self.centralwidget.setFont(font)
        self.MemoryUsage_progressBar = QProgressBar(self.centralwidget)
        self.MemoryUsage_progressBar.setObjectName(u"MemoryUsage_progressBar")
        self.MemoryUsage_progressBar.setGeometry(QRect(10, 490, 971, 23))
        self.MemoryUsage_progressBar.setValue(40)
        self.EepromMemoryUsageText = QLabel(self.centralwidget)
        self.EepromMemoryUsageText.setObjectName(u"EepromMemoryUsageText")
        self.EepromMemoryUsageText.setGeometry(QRect(10, 460, 321, 31))
        font1 = QFont()
        font1.setPointSize(12)
        self.EepromMemoryUsageText.setFont(font1)
        self.AddElementpushButton = QPushButton(self.centralwidget)
        self.AddElementpushButton.setObjectName(u"AddElementpushButton")
        self.AddElementpushButton.setGeometry(QRect(10, 420, 131, 31))
        self.DeleteElementpushButton_2 = QPushButton(self.centralwidget)
        self.DeleteElementpushButton_2.setObjectName(u"DeleteElementpushButton_2")
        self.DeleteElementpushButton_2.setGeometry(QRect(160, 420, 131, 31))
        self.EepromMemoryConfigurationText = QLabel(self.centralwidget)
        self.EepromMemoryConfigurationText.setObjectName(u"EepromMemoryConfigurationText")
        self.EepromMemoryConfigurationText.setGeometry(QRect(10, 10, 321, 41))
        font2 = QFont()
        font2.setPointSize(20)
        font2.setBold(True)
        font2.setItalic(False)
        font2.setStrikeOut(False)
        self.EepromMemoryConfigurationText.setFont(font2)
        self.DeleteAllpushButton_3 = QPushButton(self.centralwidget)
        self.DeleteAllpushButton_3.setObjectName(u"DeleteAllpushButton_3")
        self.DeleteAllpushButton_3.setGeometry(QRect(890, 420, 101, 31))
        self.EepromText = QLabel(self.centralwidget)
        self.EepromText.setObjectName(u"EepromText")
        self.EepromText.setGeometry(QRect(10, 530, 47, 16))
        font3 = QFont()
        font3.setBold(True)
        self.EepromText.setFont(font3)
        self.EepromUsageText = QLabel(self.centralwidget)
        self.EepromUsageText.setObjectName(u"EepromUsageText")
        self.EepromUsageText.setGeometry(QRect(150, 530, 47, 16))
        self.EepromUsageText.setFont(font3)
        self.EepromFreeText = QLabel(self.centralwidget)
        self.EepromFreeText.setObjectName(u"EepromFreeText")
        self.EepromFreeText.setGeometry(QRect(290, 530, 31, 21))
        self.EepromFreeText.setFont(font3)
        self.EepromSize = QLabel(self.centralwidget)
        self.EepromSize.setObjectName(u"EepromSize")
        self.EepromSize.setGeometry(QRect(60, 530, 61, 16))
        self.EepromSize.setScaledContents(False)
        self.EepromSize.setWordWrap(False)
        self.EepromSize.setOpenExternalLinks(False)
        self.EepromSize_Used = QLabel(self.centralwidget)
        self.EepromSize_Used.setObjectName(u"EepromSize_Used")
        self.EepromSize_Used.setGeometry(QRect(200, 530, 47, 16))
        self.EepromSize_Used.setScaledContents(False)
        self.EepromSize_Used.setWordWrap(False)
        self.EepromSize_Used.setOpenExternalLinks(False)
        self.EepromSize_Free = QLabel(self.centralwidget)
        self.EepromSize_Free.setObjectName(u"EepromSize_Free")
        self.EepromSize_Free.setGeometry(QRect(330, 530, 47, 21))
        self.EepromSize_Free.setScaledContents(False)
        self.EepromSize_Free.setWordWrap(False)
        self.EepromSize_Free.setOpenExternalLinks(False)
        self.VariablesTableWidget = QTableWidget(self.centralwidget)
        if (self.VariablesTableWidget.columnCount() < 6):
            self.VariablesTableWidget.setColumnCount(6)
        __qtablewidgetitem = QTableWidgetItem()
        self.VariablesTableWidget.setHorizontalHeaderItem(0, __qtablewidgetitem)
        __qtablewidgetitem1 = QTableWidgetItem()
        self.VariablesTableWidget.setHorizontalHeaderItem(1, __qtablewidgetitem1)
        __qtablewidgetitem2 = QTableWidgetItem()
        self.VariablesTableWidget.setHorizontalHeaderItem(2, __qtablewidgetitem2)
        __qtablewidgetitem3 = QTableWidgetItem()
        self.VariablesTableWidget.setHorizontalHeaderItem(3, __qtablewidgetitem3)
        __qtablewidgetitem4 = QTableWidgetItem()
        self.VariablesTableWidget.setHorizontalHeaderItem(4, __qtablewidgetitem4)
        __qtablewidgetitem5 = QTableWidgetItem()
        self.VariablesTableWidget.setHorizontalHeaderItem(5, __qtablewidgetitem5)
        if (self.VariablesTableWidget.rowCount() < 2):
            self.VariablesTableWidget.setRowCount(2)
        __qtablewidgetitem6 = QTableWidgetItem()
        self.VariablesTableWidget.setVerticalHeaderItem(0, __qtablewidgetitem6)
        __qtablewidgetitem7 = QTableWidgetItem()
        self.VariablesTableWidget.setVerticalHeaderItem(1, __qtablewidgetitem7)
        __qtablewidgetitem8 = QTableWidgetItem()
        self.VariablesTableWidget.setItem(0, 0, __qtablewidgetitem8)
        __qtablewidgetitem9 = QTableWidgetItem()
        self.VariablesTableWidget.setItem(0, 1, __qtablewidgetitem9)
        __qtablewidgetitem10 = QTableWidgetItem()
        self.VariablesTableWidget.setItem(0, 2, __qtablewidgetitem10)
        __qtablewidgetitem11 = QTableWidgetItem()
        self.VariablesTableWidget.setItem(0, 3, __qtablewidgetitem11)
        __qtablewidgetitem12 = QTableWidgetItem()
        self.VariablesTableWidget.setItem(0, 4, __qtablewidgetitem12)
        __qtablewidgetitem13 = QTableWidgetItem()
        self.VariablesTableWidget.setItem(0, 5, __qtablewidgetitem13)
        __qtablewidgetitem14 = QTableWidgetItem()
        self.VariablesTableWidget.setItem(1, 0, __qtablewidgetitem14)
        __qtablewidgetitem15 = QTableWidgetItem()
        self.VariablesTableWidget.setItem(1, 1, __qtablewidgetitem15)
        __qtablewidgetitem16 = QTableWidgetItem()
        self.VariablesTableWidget.setItem(1, 2, __qtablewidgetitem16)
        __qtablewidgetitem17 = QTableWidgetItem()
        self.VariablesTableWidget.setItem(1, 3, __qtablewidgetitem17)
        __qtablewidgetitem18 = QTableWidgetItem()
        self.VariablesTableWidget.setItem(1, 4, __qtablewidgetitem18)
        __qtablewidgetitem19 = QTableWidgetItem()
        self.VariablesTableWidget.setItem(1, 5, __qtablewidgetitem19)
        self.VariablesTableWidget.setObjectName(u"VariablesTableWidget")
        self.VariablesTableWidget.setGeometry(QRect(10, 70, 980, 330))
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.VariablesTableWidget.sizePolicy().hasHeightForWidth())
        self.VariablesTableWidget.setSizePolicy(sizePolicy)
        self.VariablesTableWidget.setMinimumSize(QSize(980, 330))
        self.VariablesTableWidget.setMaximumSize(QSize(980, 330))
        self.VariablesTableWidget.setAcceptDrops(False)
        self.VariablesTableWidget.setSizeAdjustPolicy(QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.VariablesTableWidget.setAlternatingRowColors(True)
        self.VariablesTableWidget.setTextElideMode(Qt.ElideLeft)
        self.VariablesTableWidget.setVerticalScrollMode(QAbstractItemView.ScrollPerItem)
        self.VariablesTableWidget.setGridStyle(Qt.NoPen)
        self.VariablesTableWidget.setSortingEnabled(True)
        self.VariablesTableWidget.setRowCount(2)
        self.VariablesTableWidget.horizontalHeader().setVisible(True)
        self.VariablesTableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.VariablesTableWidget.horizontalHeader().setMinimumSectionSize(40)
        self.VariablesTableWidget.horizontalHeader().setHighlightSections(True)
        self.VariablesTableWidget.horizontalHeader().setProperty(u"showSortIndicator", True)
        self.VariablesTableWidget.verticalHeader().setVisible(False)
        self.VariablesTableWidget.verticalHeader().setCascadingSectionResizes(True)
        self.VariablesTableWidget.verticalHeader().setMinimumSectionSize(20)
        self.VariablesTableWidget.verticalHeader().setHighlightSections(True)
        self.VariablesTableWidget.verticalHeader().setProperty(u"showSortIndicator", False)
        self.VariablesTableWidget.verticalHeader().setStretchLastSection(False)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1000, 21))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuEdit = QMenu(self.menubar)
        self.menuEdit.setObjectName(u"menuEdit")
        self.menuGenerate = QMenu(self.menubar)
        self.menuGenerate.setObjectName(u"menuGenerate")
        self.menuConfigure = QMenu(self.menubar)
        self.menuConfigure.setObjectName(u"menuConfigure")
        self.menuHelp = QMenu(self.menubar)
        self.menuHelp.setObjectName(u"menuHelp")
        self.menuValidate = QMenu(self.menubar)
        self.menuValidate.setObjectName(u"menuValidate")
        MainWindow.setMenuBar(self.menubar)
        self.MemoryUsage_statusbar = QStatusBar(MainWindow)
        self.MemoryUsage_statusbar.setObjectName(u"MemoryUsage_statusbar")
        MainWindow.setStatusBar(self.MemoryUsage_statusbar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuConfigure.menuAction())
        self.menubar.addAction(self.menuValidate.menuAction())
        self.menubar.addAction(self.menuGenerate.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_as)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionImport)
        self.menuFile.addAction(self.actionExport)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit_2)
        self.menuEdit.addAction(self.actionAdd_new_element)
        self.menuEdit.addAction(self.actionDelete_an_element)
        self.menuEdit.addAction(self.actionDelete_all)
        self.menuGenerate.addAction(self.actionGenerate_files)
        self.menuGenerate.addAction(self.actionGenerate_h_files)
        self.menuGenerate.addAction(self.actionGenerate_xml_files)
        self.menuGenerate.addAction(self.actionGenerate_all)
        self.menuConfigure.addAction(self.actionEeprom)
        self.menuHelp.addAction(self.actionUser_Manual)
        self.menuHelp.addAction(self.actionInformation)
        self.menuValidate.addAction(self.actionValidate_variables)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Eeprom Configurator", None))
        self.actionNew.setText(QCoreApplication.translate("MainWindow", u"New", None))
        self.actionSave.setText(QCoreApplication.translate("MainWindow", u"Save", None))
        self.actionSave_as.setText(QCoreApplication.translate("MainWindow", u"Save as", None))
        self.actionQuit.setText(QCoreApplication.translate("MainWindow", u"Quit", None))
        self.actionGenerate_files.setText(QCoreApplication.translate("MainWindow", u"Generate .c files", None))
        self.actionUser_.setText(QCoreApplication.translate("MainWindow", u"Eeprom memory", None))
        self.actionUser_Manual_2.setText(QCoreApplication.translate("MainWindow", u"User Manual", None))
        self.actionInfo.setText(QCoreApplication.translate("MainWindow", u"Info", None))
        self.actionEeprom.setText(QCoreApplication.translate("MainWindow", u"Eeprom parameters", None))
        self.actionUser_Manual.setText(QCoreApplication.translate("MainWindow", u"User Manual", None))
        self.actionInformation.setText(QCoreApplication.translate("MainWindow", u"Info", None))
        self.actionImport.setText(QCoreApplication.translate("MainWindow", u"Import", None))
        self.actionExport.setText(QCoreApplication.translate("MainWindow", u"Export", None))
        self.actionQuit_2.setText(QCoreApplication.translate("MainWindow", u"Quit", None))
        self.actionAdd_new_element.setText(QCoreApplication.translate("MainWindow", u"Add new element", None))
        self.actionDelete_an_element.setText(QCoreApplication.translate("MainWindow", u"Delete an element", None))
        self.actionDelete_all.setText(QCoreApplication.translate("MainWindow", u"Delete all", None))
        self.actionGenerate_h_files.setText(QCoreApplication.translate("MainWindow", u"Generate .h files", None))
        self.actionGenerate_xml_files.setText(QCoreApplication.translate("MainWindow", u"Generate .xml files", None))
        self.actionValidate_variables.setText(QCoreApplication.translate("MainWindow", u"Project", None))
        self.actionGenerate_all.setText(QCoreApplication.translate("MainWindow", u"Generate all", None))
        self.EepromMemoryUsageText.setText(QCoreApplication.translate("MainWindow", u"Eeprom Memory Usage", None))
        self.AddElementpushButton.setText(QCoreApplication.translate("MainWindow", u"Add new element", None))
        self.DeleteElementpushButton_2.setText(QCoreApplication.translate("MainWindow", u"Delet an element", None))
        self.EepromMemoryConfigurationText.setText(QCoreApplication.translate("MainWindow", u"Eeprom Configurator", None))
        self.DeleteAllpushButton_3.setText(QCoreApplication.translate("MainWindow", u"Delet all", None))
        self.EepromText.setText(QCoreApplication.translate("MainWindow", u"Eeprom:", None))
        self.EepromUsageText.setText(QCoreApplication.translate("MainWindow", u"Usaged:", None))
        self.EepromFreeText.setText(QCoreApplication.translate("MainWindow", u"Free:", None))
        self.EepromSize.setText(QCoreApplication.translate("MainWindow", u"512 kBytes", None))
        self.EepromSize_Used.setText(QCoreApplication.translate("MainWindow", u"40%", None))
        self.EepromSize_Free.setText(QCoreApplication.translate("MainWindow", u"60%", None))
        ___qtablewidgetitem = self.VariablesTableWidget.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("MainWindow", u"Index", None))
        ___qtablewidgetitem1 = self.VariablesTableWidget.horizontalHeaderItem(1)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("MainWindow", u"Name", None))
        ___qtablewidgetitem2 = self.VariablesTableWidget.horizontalHeaderItem(2)
        ___qtablewidgetitem2.setText(QCoreApplication.translate("MainWindow", u"Type", None))
        ___qtablewidgetitem3 = self.VariablesTableWidget.horizontalHeaderItem(3)
        ___qtablewidgetitem3.setText(QCoreApplication.translate("MainWindow", u"Direction", None))
        ___qtablewidgetitem4 = self.VariablesTableWidget.horizontalHeaderItem(4)
        ___qtablewidgetitem4.setText(QCoreApplication.translate("MainWindow", u"Init Value", None))
        ___qtablewidgetitem5 = self.VariablesTableWidget.horizontalHeaderItem(5)
        ___qtablewidgetitem5.setText(QCoreApplication.translate("MainWindow", u"Comment", None))
        ___qtablewidgetitem6 = self.VariablesTableWidget.verticalHeaderItem(0)
        ___qtablewidgetitem6.setText(QCoreApplication.translate("MainWindow", u"1", None))
        ___qtablewidgetitem7 = self.VariablesTableWidget.verticalHeaderItem(1)
        ___qtablewidgetitem7.setText(QCoreApplication.translate("MainWindow", u"2", None))

        __sortingEnabled = self.VariablesTableWidget.isSortingEnabled()
        self.VariablesTableWidget.setSortingEnabled(False)
        ___qtablewidgetitem8 = self.VariablesTableWidget.item(0, 0)
        ___qtablewidgetitem8.setText(QCoreApplication.translate("MainWindow", u"1", None))
        ___qtablewidgetitem9 = self.VariablesTableWidget.item(0, 1)
        ___qtablewidgetitem9.setText(QCoreApplication.translate("MainWindow", u"MOTOR_REAR_LIMIT", None))
        ___qtablewidgetitem10 = self.VariablesTableWidget.item(0, 2)
        ___qtablewidgetitem10.setText(QCoreApplication.translate("MainWindow", u"uint16_t", None))
        ___qtablewidgetitem11 = self.VariablesTableWidget.item(0, 3)
        ___qtablewidgetitem11.setText(QCoreApplication.translate("MainWindow", u"0x7FF4", None))
        ___qtablewidgetitem12 = self.VariablesTableWidget.item(0, 4)
        ___qtablewidgetitem12.setText(QCoreApplication.translate("MainWindow", u"1", None))
        ___qtablewidgetitem13 = self.VariablesTableWidget.item(0, 5)
        ___qtablewidgetitem13.setText(QCoreApplication.translate("MainWindow", u"Rear limit of seat motor ", None))
        ___qtablewidgetitem14 = self.VariablesTableWidget.item(1, 0)
        ___qtablewidgetitem14.setText(QCoreApplication.translate("MainWindow", u"2", None))
        ___qtablewidgetitem15 = self.VariablesTableWidget.item(1, 1)
        ___qtablewidgetitem15.setText(QCoreApplication.translate("MainWindow", u"MOTOR_FRONT_LIMIT", None))
        ___qtablewidgetitem16 = self.VariablesTableWidget.item(1, 2)
        ___qtablewidgetitem16.setText(QCoreApplication.translate("MainWindow", u"uint16_t", None))
        ___qtablewidgetitem17 = self.VariablesTableWidget.item(1, 3)
        ___qtablewidgetitem17.setText(QCoreApplication.translate("MainWindow", u"0x7FF6", None))
        ___qtablewidgetitem18 = self.VariablesTableWidget.item(1, 4)
        ___qtablewidgetitem18.setText(QCoreApplication.translate("MainWindow", u"65535", None))
        ___qtablewidgetitem19 = self.VariablesTableWidget.item(1, 5)
        ___qtablewidgetitem19.setText(QCoreApplication.translate("MainWindow", u"Front limit of seat motor ", None))
        self.VariablesTableWidget.setSortingEnabled(__sortingEnabled)

        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuEdit.setTitle(QCoreApplication.translate("MainWindow", u"Edit", None))
        self.menuGenerate.setTitle(QCoreApplication.translate("MainWindow", u"Generate", None))
        self.menuConfigure.setTitle(QCoreApplication.translate("MainWindow", u"Configure", None))
        self.menuHelp.setTitle(QCoreApplication.translate("MainWindow", u"Help", None))
        self.menuValidate.setTitle(QCoreApplication.translate("MainWindow", u"Validate", None))
    # retranslateUi

