# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'Variable_configuration_dialog.ui'
##
## Created by: Qt User Interface Compiler version 6.11.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractButton, QApplication, QCheckBox, QComboBox,
    QDialog, QDialogButtonBox, QLabel, QLineEdit,
    QSizePolicy, QWidget)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        if not Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.resize(402, 431)
        self.VariableAcceptRejectButton = QDialogButtonBox(Dialog)
        self.VariableAcceptRejectButton.setObjectName(u"VariableAcceptRejectButton")
        self.VariableAcceptRejectButton.setGeometry(QRect(30, 390, 341, 32))
        self.VariableAcceptRejectButton.setOrientation(Qt.Horizontal)
        self.VariableAcceptRejectButton.setStandardButtons(QDialogButtonBox.Cancel|QDialogButtonBox.Ok)
        self.VariableParametersText = QLabel(Dialog)
        self.VariableParametersText.setObjectName(u"VariableParametersText")
        self.VariableParametersText.setGeometry(QRect(10, 10, 221, 41))
        font = QFont()
        font.setPointSize(18)
        self.VariableParametersText.setFont(font)
        self.VariableNameText = QLabel(Dialog)
        self.VariableNameText.setObjectName(u"VariableNameText")
        self.VariableNameText.setGeometry(QRect(40, 60, 61, 31))
        font1 = QFont()
        font1.setPointSize(12)
        self.VariableNameText.setFont(font1)
        self.VariableTypeText = QLabel(Dialog)
        self.VariableTypeText.setObjectName(u"VariableTypeText")
        self.VariableTypeText.setGeometry(QRect(40, 100, 61, 31))
        self.VariableTypeText.setFont(font1)
        self.VariableDirectionText = QLabel(Dialog)
        self.VariableDirectionText.setObjectName(u"VariableDirectionText")
        self.VariableDirectionText.setGeometry(QRect(40, 180, 71, 31))
        self.VariableDirectionText.setFont(font1)
        self.VariableInitValueText = QLabel(Dialog)
        self.VariableInitValueText.setObjectName(u"VariableInitValueText")
        self.VariableInitValueText.setGeometry(QRect(40, 220, 71, 31))
        self.VariableInitValueText.setFont(font1)
        self.VariableCommentText = QLabel(Dialog)
        self.VariableCommentText.setObjectName(u"VariableCommentText")
        self.VariableCommentText.setGeometry(QRect(40, 260, 81, 31))
        self.VariableCommentText.setFont(font1)
        self.VariableTypeComboBox = QComboBox(Dialog)
        self.VariableTypeComboBox.addItem("")
        self.VariableTypeComboBox.addItem("")
        self.VariableTypeComboBox.addItem("")
        self.VariableTypeComboBox.addItem("")
        self.VariableTypeComboBox.addItem("")
        self.VariableTypeComboBox.addItem("")
        self.VariableTypeComboBox.addItem("")
        self.VariableTypeComboBox.addItem("")
        self.VariableTypeComboBox.addItem("")
        self.VariableTypeComboBox.addItem("")
        self.VariableTypeComboBox.setObjectName(u"VariableTypeComboBox")
        self.VariableTypeComboBox.setGeometry(QRect(120, 100, 241, 31))
        self.VariableTypeComboBox.setFont(font1)
        self.VariableName = QLineEdit(Dialog)
        self.VariableName.setObjectName(u"VariableName")
        self.VariableName.setGeometry(QRect(120, 60, 241, 31))
        self.VariableName.setFont(font1)
        self.VariableDirection = QLineEdit(Dialog)
        self.VariableDirection.setObjectName(u"VariableDirection")
        self.VariableDirection.setGeometry(QRect(120, 180, 241, 31))
        self.VariableDirection.setFont(font1)
        self.VariableInitValue = QLineEdit(Dialog)
        self.VariableInitValue.setObjectName(u"VariableInitValue")
        self.VariableInitValue.setGeometry(QRect(120, 220, 111, 31))
        self.VariableInitValue.setFont(font1)
        self.VariableInitValue.setDragEnabled(False)
        self.VariableInitValue.setReadOnly(False)
        self.VariableInitValue.setClearButtonEnabled(False)
        self.VariableComment = QLineEdit(Dialog)
        self.VariableComment.setObjectName(u"VariableComment")
        self.VariableComment.setGeometry(QRect(120, 260, 241, 111))
        font2 = QFont()
        font2.setPointSize(12)
        font2.setKerning(True)
        font2.setStyleStrategy(QFont.PreferDefault)
        self.VariableComment.setFont(font2)
        self.VariableComment.setLayoutDirection(Qt.LeftToRight)
        self.VariableComment.setAutoFillBackground(False)
        self.VariableComment.setInputMethodHints(Qt.ImhMultiLine)
        self.VariableComment.setFrame(True)
        self.VariableComment.setEchoMode(QLineEdit.Normal)
        self.VariableComment.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.VariableComment.setDragEnabled(False)
        self.VariableComment.setPlaceholderText(u"")
        self.VariableComment.setClearButtonEnabled(False)
        self.WriteVariableCheckBox = QCheckBox(Dialog)
        self.WriteVariableCheckBox.setObjectName(u"WriteVariableCheckBox")
        self.WriteVariableCheckBox.setGeometry(QRect(250, 230, 111, 17))
        font3 = QFont()
        font3.setPointSize(10)
        self.WriteVariableCheckBox.setFont(font3)
        self.WriteVariableCheckBox.setCheckable(True)
        self.WriteVariableCheckBox.setChecked(True)
        self.ArrayCheckBox = QCheckBox(Dialog)
        self.ArrayCheckBox.setObjectName(u"ArrayCheckBox")
        self.ArrayCheckBox.setGeometry(QRect(250, 150, 70, 17))
        self.ArrayCheckBox.setFont(font3)
        self.ArrayCheckBox.setChecked(True)
        self.VariableElementsText = QLabel(Dialog)
        self.VariableElementsText.setObjectName(u"VariableElementsText")
        self.VariableElementsText.setGeometry(QRect(40, 140, 71, 31))
        self.VariableElementsText.setFont(font1)
        self.VariableElements = QLineEdit(Dialog)
        self.VariableElements.setObjectName(u"VariableElements")
        self.VariableElements.setGeometry(QRect(120, 140, 111, 31))

        self.retranslateUi(Dialog)
        self.VariableAcceptRejectButton.accepted.connect(Dialog.accept)
        self.VariableAcceptRejectButton.rejected.connect(Dialog.reject)
        self.ArrayCheckBox.toggled.connect(self.VariableElements.setVisible)
        self.WriteVariableCheckBox.toggled.connect(self.VariableInitValue.setVisible)

        QMetaObject.connectSlotsByName(Dialog)
    # setupUi

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QCoreApplication.translate("Dialog", u"Variable configuration", None))
        self.VariableParametersText.setText(QCoreApplication.translate("Dialog", u"Variable Parameters", None))
        self.VariableNameText.setText(QCoreApplication.translate("Dialog", u"Name:", None))
        self.VariableTypeText.setText(QCoreApplication.translate("Dialog", u"Type:", None))
        self.VariableDirectionText.setText(QCoreApplication.translate("Dialog", u"Direction:", None))
        self.VariableInitValueText.setText(QCoreApplication.translate("Dialog", u"Init value:", None))
        self.VariableCommentText.setText(QCoreApplication.translate("Dialog", u"Comment:", None))
        self.VariableTypeComboBox.setItemText(0, QCoreApplication.translate("Dialog", u"uint8_t", None))
        self.VariableTypeComboBox.setItemText(1, QCoreApplication.translate("Dialog", u"uint16_t", None))
        self.VariableTypeComboBox.setItemText(2, QCoreApplication.translate("Dialog", u"uint32_t", None))
        self.VariableTypeComboBox.setItemText(3, QCoreApplication.translate("Dialog", u"uint64_t", None))
        self.VariableTypeComboBox.setItemText(4, QCoreApplication.translate("Dialog", u"int8_t", None))
        self.VariableTypeComboBox.setItemText(5, QCoreApplication.translate("Dialog", u"int16_t", None))
        self.VariableTypeComboBox.setItemText(6, QCoreApplication.translate("Dialog", u"int32_t", None))
        self.VariableTypeComboBox.setItemText(7, QCoreApplication.translate("Dialog", u"int64_t", None))
        self.VariableTypeComboBox.setItemText(8, QCoreApplication.translate("Dialog", u"float", None))
        self.VariableTypeComboBox.setItemText(9, QCoreApplication.translate("Dialog", u"char", None))

        self.WriteVariableCheckBox.setText(QCoreApplication.translate("Dialog", u"Write variable", None))
        self.ArrayCheckBox.setText(QCoreApplication.translate("Dialog", u"Array", None))
        self.VariableElementsText.setText(QCoreApplication.translate("Dialog", u"Elements:", None))
    # retranslateUi

